array_layout = "Visual"
array_width = 0
chain_indent = "Visual"
chain_one_line_max = 0
closure_block_indent_threshold = -1
comment_width = 120
condense_wildcard_suffices = true
control_brace_style = "AlwaysSameLine"
disable_all_formatting = false
error_on_line_overflow = true
fn_args_density = "Vertical"
fn_args_layout = "Visual"
fn_args_paren_newline = false
fn_brace_style = "AlwaysNextLine"
fn_call_style = "Visual"
fn_call_width = 0
fn_empty_single_line = false
fn_return_indent = "WithWhereClause"
fn_single_line = false
force_explicit_abi = true
force_format_strings = true
format_strings = true
generics_indent = "Visual"
generics_style = "Default"
hard_tabs = false
impl_empty_single_line = false
indent_match_arms = true
item_brace_style = "AlwaysNextLine"
match_block_trailing_comma = true
max_width = 120
newline_style = "Unix"
normalize_comments = true
reorder_imported_names = true
reorder_imports = true
single_line_if_else_max_width = 0
skip_children = true
space_after_bound_colon = true
space_after_type_annotation_colon = true
space_before_bound = false
space_before_type_annotation = false
spaces_around_ranges = false
spaces_within_angle_brackets = false
spaces_within_parens = false
spaces_within_square_brackets = false
struct_lit_multiline_style = "ForceMulti"
struct_lit_style = "Visual"
struct_lit_width = 0
struct_variant_width = 0
tab_spaces = 4
take_source_hints = false
trailing_comma = "Always"
type_punctuation_density = "Wide"
use_try_shorthand = true
where_density = "Vertical"
where_indent = "Visual"
where_layout = "Vertical"
where_pred_indent = "Visual"
where_style = "Default"
wrap_comments = true
wrap_match_arms = true
write_mode = "Replace"
