language: rust
sudo: false

rust:
  - nightly
  - beta
  - stable

before_script:
  - pip install -v 'travis-cargo<0.2' --user
  - (cargo install rustfmt || true)
  - export PATH=$HOME/.cargo/bin:$HOME/.local/bin:$PATH
script:
  - |
      cargo fmt -- --write-mode=diff &&
      cargo build --features from_url &&
      cargo test --features from_url &&
      travis-cargo --only stable doc
after_success:
  - travis-cargo --only stable doc-upload

env:
  global:
    - TRAVIS_CARGO_NIGHTLY_FEATURE=""
