[package]
name = "rss-rs"
version = "0.3.0"
authors = ["James Hurst <jh.jameshurst@gmail.com>"]
description = "A fast RSS feed parser"
repository = "https://github.com/jameshurst/rss-rs"
documentation = "https://jameshurst.github.io/rss-rs/rss/"
license = "MIT"
readme = "README.md"
keywords = ["rss", "feed", "parser", "parsing"]

[lib]
name = "rss"
path = "src/lib.rs"

[dependencies]
quick-xml = "0.4"
