[package]

name = "rss"
version = "0.0.3"
authors = ["Corey Farwell <coreyf@rwell.org>"]
license = "Apache-2.0"
repository = "https://github.com/frewsxcv/rust-rss"
description = "Read/write for RSS"
exclude = ["test-data/"]


[dependencies]
RustyXML = "0.1.0"
