[package]
name = "rss-rs"
version = "0.1.0"
authors = ["James Hurst <jh.jameshurst@gmail.com>"]
description = "Library for parsing RSS feeds"
repository = "https://github.com/jameshurst/rss-rs"
license = "MIT"
readme = "README.md"
keywords = ["rss", "feed", "parser", "parsing"]

[lib]
name = "rss"
path = "src/lib.rs"

[features]
default = ["xml-rs"]

[dependencies]
xml-rs = {version = "0.3", optional = true}
quick-xml = {version = "0.3", optional = true}
