[package]
name = "rss"
version = "0.4.0"
authors = ["James Hurst <jh.jameshurst@gmail.com>", "Corey Farwell <coreyf@rwell.org>"]
description = "A fast RSS feed parser"
repository = "https://github.com/rust-syndication/rss"
documentation = "https://rust-syndication.github.io/rss/rss/"
license = "MIT"
readme = "README.md"
keywords = ["rss", "feed", "parser", "parsing"]
include = ["src/*", "Cargo.toml", "LICENSE", "README.md"]

[dependencies]
quick-xml = "0.4"
