[package]

name = "rss"
version = "0.0.2"
authors = ["Corey Farwell <coreyf@rwell.org>"]
license = "Apache-2.0"
repository = "https://github.com/frewsxcv/rust-rss"


[dependencies]
RustyXML = "0.1.0"
